# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Projects/ALBUS/ALBUS_ionosphere

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Projects/ALBUS/ALBUS_ionosphere

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Projects/ALBUS/ALBUS_ionosphere/CMakeFiles /home/user/Projects/ALBUS/ALBUS_ionosphere//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Projects/ALBUS/ALBUS_ionosphere/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main_distclean

# Build rule for target.
main_distclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_distclean
.PHONY : main_distclean

# fast build rule for target.
main_distclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_distclean.dir/build.make CMakeFiles/main_distclean.dir/build
.PHONY : main_distclean/fast

#=============================================================================
# Target rules for targets named PIMrunner_target

# Build rule for target.
PIMrunner_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PIMrunner_target
.PHONY : PIMrunner_target

# fast build rule for target.
PIMrunner_target/fast:
	$(MAKE) $(MAKESILENT) -f C++/CMakeFiles/PIMrunner_target.dir/build.make C++/CMakeFiles/PIMrunner_target.dir/build
.PHONY : PIMrunner_target/fast

#=============================================================================
# Target rules for targets named vex_to_sky2_target

# Build rule for target.
vex_to_sky2_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vex_to_sky2_target
.PHONY : vex_to_sky2_target

# fast build rule for target.
vex_to_sky2_target/fast:
	$(MAKE) $(MAKESILENT) -f C++/CMakeFiles/vex_to_sky2_target.dir/build.make C++/CMakeFiles/vex_to_sky2_target.dir/build
.PHONY : vex_to_sky2_target/fast

#=============================================================================
# Target rules for targets named jmavex_obj

# Build rule for target.
jmavex_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jmavex_obj
.PHONY : jmavex_obj

# fast build rule for target.
jmavex_obj/fast:
	$(MAKE) $(MAKESILENT) -f C++/vex_to_sky2/CMakeFiles/jmavex_obj.dir/build.make C++/vex_to_sky2/CMakeFiles/jmavex_obj.dir/build
.PHONY : jmavex_obj/fast

#=============================================================================
# Target rules for targets named jmavex_shared

# Build rule for target.
jmavex_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jmavex_shared
.PHONY : jmavex_shared

# fast build rule for target.
jmavex_shared/fast:
	$(MAKE) $(MAKESILENT) -f C++/vex_to_sky2/CMakeFiles/jmavex_shared.dir/build.make C++/vex_to_sky2/CMakeFiles/jmavex_shared.dir/build
.PHONY : jmavex_shared/fast

#=============================================================================
# Target rules for targets named jmavex_static

# Build rule for target.
jmavex_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jmavex_static
.PHONY : jmavex_static

# fast build rule for target.
jmavex_static/fast:
	$(MAKE) $(MAKESILENT) -f C++/vex_to_sky2/CMakeFiles/jmavex_static.dir/build.make C++/vex_to_sky2/CMakeFiles/jmavex_static.dir/build
.PHONY : jmavex_static/fast

#=============================================================================
# Target rules for targets named ell_coord_converter

# Build rule for target.
ell_coord_converter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ell_coord_converter
.PHONY : ell_coord_converter

# fast build rule for target.
ell_coord_converter/fast:
	$(MAKE) $(MAKESILENT) -f C++/vex_to_sky2/CMakeFiles/ell_coord_converter.dir/build.make C++/vex_to_sky2/CMakeFiles/ell_coord_converter.dir/build
.PHONY : ell_coord_converter/fast

#=============================================================================
# Target rules for targets named vexplus

# Build rule for target.
vexplus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vexplus
.PHONY : vexplus

# fast build rule for target.
vexplus/fast:
	$(MAKE) $(MAKESILENT) -f C++/vex_to_sky2/vexplus/CMakeFiles/vexplus.dir/build.make C++/vex_to_sky2/vexplus/CMakeFiles/vexplus.dir/build
.PHONY : vexplus/fast

#=============================================================================
# Target rules for targets named vexplus_static

# Build rule for target.
vexplus_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vexplus_static
.PHONY : vexplus_static

# fast build rule for target.
vexplus_static/fast:
	$(MAKE) $(MAKESILENT) -f C++/vex_to_sky2/vexplus/CMakeFiles/vexplus_static.dir/build.make C++/vex_to_sky2/vexplus/CMakeFiles/vexplus_static.dir/build
.PHONY : vexplus_static/fast

#=============================================================================
# Target rules for targets named mim

# Build rule for target.
mim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mim
.PHONY : mim

# fast build rule for target.
mim/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/mim.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/mim.dir/build
.PHONY : mim/fast

#=============================================================================
# Target rules for targets named lofar

# Build rule for target.
lofar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar
.PHONY : lofar

# fast build rule for target.
lofar/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar.dir/build
.PHONY : lofar/fast

#=============================================================================
# Target rules for targets named lofar2

# Build rule for target.
lofar2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar2
.PHONY : lofar2

# fast build rule for target.
lofar2/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar2.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar2.dir/build
.PHONY : lofar2/fast

#=============================================================================
# Target rules for targets named lofar3

# Build rule for target.
lofar3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar3
.PHONY : lofar3

# fast build rule for target.
lofar3/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar3.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar3.dir/build
.PHONY : lofar3/fast

#=============================================================================
# Target rules for targets named lofar4

# Build rule for target.
lofar4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar4
.PHONY : lofar4

# fast build rule for target.
lofar4/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar4.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar4.dir/build
.PHONY : lofar4/fast

#=============================================================================
# Target rules for targets named lofar5

# Build rule for target.
lofar5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar5
.PHONY : lofar5

# fast build rule for target.
lofar5/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar5.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar5.dir/build
.PHONY : lofar5/fast

#=============================================================================
# Target rules for targets named lofar6

# Build rule for target.
lofar6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar6
.PHONY : lofar6

# fast build rule for target.
lofar6/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar6.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar6.dir/build
.PHONY : lofar6/fast

#=============================================================================
# Target rules for targets named lofar7

# Build rule for target.
lofar7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar7
.PHONY : lofar7

# fast build rule for target.
lofar7/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar7.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar7.dir/build
.PHONY : lofar7/fast

#=============================================================================
# Target rules for targets named lofar8

# Build rule for target.
lofar8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar8
.PHONY : lofar8

# fast build rule for target.
lofar8/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar8.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar8.dir/build
.PHONY : lofar8/fast

#=============================================================================
# Target rules for targets named lofar9

# Build rule for target.
lofar9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar9
.PHONY : lofar9

# fast build rule for target.
lofar9/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar9.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar9.dir/build
.PHONY : lofar9/fast

#=============================================================================
# Target rules for targets named lofar10

# Build rule for target.
lofar10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lofar10
.PHONY : lofar10

# fast build rule for target.
lofar10/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/lofar10.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/lofar10.dir/build
.PHONY : lofar10/fast

#=============================================================================
# Target rules for targets named test_pim

# Build rule for target.
test_pim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_pim
.PHONY : test_pim

# fast build rule for target.
test_pim/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/test_pim.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/test_pim.dir/build
.PHONY : test_pim/fast

#=============================================================================
# Target rules for targets named test2_pim

# Build rule for target.
test2_pim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test2_pim
.PHONY : test2_pim

# fast build rule for target.
test2_pim/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/test2_pim.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/test2_pim.dir/build
.PHONY : test2_pim/fast

#=============================================================================
# Target rules for targets named vlba_obs

# Build rule for target.
vlba_obs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vlba_obs
.PHONY : vlba_obs

# fast build rule for target.
vlba_obs/fast:
	$(MAKE) $(MAKESILENT) -f C++/mim/test/PIMrunner/CMakeFiles/vlba_obs.dir/build.make C++/mim/test/PIMrunner/CMakeFiles/vlba_obs.dir/build
.PHONY : vlba_obs/fast

#=============================================================================
# Target rules for targets named AlbusIonosphere

# Build rule for target.
AlbusIonosphere: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlbusIonosphere
.PHONY : AlbusIonosphere

# fast build rule for target.
AlbusIonosphere/fast:
	$(MAKE) $(MAKESILENT) -f C++/AlbusIonosphere/python_attempt/CMakeFiles/AlbusIonosphere.dir/build.make C++/AlbusIonosphere/python_attempt/CMakeFiles/AlbusIonosphere.dir/build
.PHONY : AlbusIonosphere/fast

#=============================================================================
# Target rules for targets named custom_install

# Build rule for target.
custom_install: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 custom_install
.PHONY : custom_install

# fast build rule for target.
custom_install/fast:
	$(MAKE) $(MAKESILENT) -f C++/AlbusIonosphere/python_attempt/CMakeFiles/custom_install.dir/build.make C++/AlbusIonosphere/python_attempt/CMakeFiles/custom_install.dir/build
.PHONY : custom_install/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) $(MAKESILENT) -f C++/AlbusIonosphere/python_attempt/CMakeFiles/distclean.dir/build.make C++/AlbusIonosphere/python_attempt/CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AlbusIonosphere"
	@echo "... PIMrunner_target"
	@echo "... custom_install"
	@echo "... distclean"
	@echo "... main_distclean"
	@echo "... vex_to_sky2_target"
	@echo "... ell_coord_converter"
	@echo "... jmavex_obj"
	@echo "... jmavex_shared"
	@echo "... jmavex_static"
	@echo "... lofar"
	@echo "... lofar10"
	@echo "... lofar2"
	@echo "... lofar3"
	@echo "... lofar4"
	@echo "... lofar5"
	@echo "... lofar6"
	@echo "... lofar7"
	@echo "... lofar8"
	@echo "... lofar9"
	@echo "... mim"
	@echo "... test2_pim"
	@echo "... test_pim"
	@echo "... vexplus"
	@echo "... vexplus_static"
	@echo "... vlba_obs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

